apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jYm9jOGU0dWNzcTYudXMtd2VzdC0yLnJkcy5hbWF6b25hd3MuY29t
  db_username: YWRtaW4=
  db_password: Y2xvdWQxMjM=
